### ISSUE TITLE
 AnnotateFeatures

### ISSUE THREAD

**Issue by 1269376398** [zhanghao-njmu/SCP#158]
data("pancreas_sub")
DEGs <- pancreas_sub@tools$DEtest_CellType$AllMarkers_wilcox
DEGs <- DEGs[with(DEGs, avg_log2FC > 1 & p_val_adj < 0.05), ]
pancreas_sub <- AnnotateFeatures(pancreas_sub, species = "Mus_musculus", db = c("TF", "SP"))
Species: Mus_musculus

Loading cached db: TF version:AnimalTFDB4 nterm:2 created:2023-09-07 10:54:23
Error in aggregate.data.frame(as.data.frame(x), ...) : 
  no rows to aggregate

I want to learn how to solve this?

**Comment by realzehuali** [comment]
same issue

**Comment by luan99kk** [comment]
same issue

**Comment by zhanghao-njmu** [comment]
I'm sorry, this error occurred because an incorrect database name was used. SCP changed the name of the SP database to CSPA in version 0.5 to differentiate it from another surface protein database called Surfaceome. However, the readme file was not updated to reflect this change, resulting in the error. 

I have already updated the readme file. Please replace "SP" with "CSPA" in your current code.

**Comment by luan99kk** [comment]
> 
Thanks for your reply. Thank you for your hard work

**Comment by realzehuali** [comment]
Thanks for your reply. Thank you for your hard work
