### ISSUE TITLE
Question related with package

### ISSUE THREAD

**Issue by Streisenberg** [zhanghao-njmu/SCP#80]
Hi,

Thank you for such a fantastic tool.

While using the package, I had a few questions in mind.

- Can we use other databases such as HALLMARK, Reactome, and Kegg apart from GO_DB used in the ExpHeatMap function? Or does the package only support the Gene Ontology database? If so, would you like to add it in future updates?

- We noticed that the package does not receive a rank file during enrichment. As I understand it, we are using the subset of the genes resulting from the RunDETest function. Shouldn't all genes be included in analyzes like pathway analysis?

Best,
Enes

**Comment by zhanghao-njmu** [comment]
The same questions have already been answered in another issue #81 @Streisenberg

**Comment by Streisenberg** [comment]
Hi Hao, thank you for your responses and your package. I have some other questions about the package.

1) I want to use Hallmark Pathways for my ExpHeatMap db with Kegg and GO_BP. When I check the PrepareDB function I could not see a way to prepare my own database manually. I saw that we could prepare databases that already supported db’s for automatically. Is there any way to add Hallmark to db or How can we create our Hallmark Pathways db?

2) In GroupHeatMap functions:

    a) While I am using the GroupHeatMap function, I can not change the color of cell_annotation. I tried to change either cell_palette or cell_palcolor but it did not affect the plot How can I change the color of cell_annotation params?

    b) When we add dot and background colors at the same time, dot colors are slightly darker than the background color. But did not give us misleading visualization since the legend shows a score gradient?

    c) Is there any way to set the upper and lower limits of Violin Plots that comes from the cell_annotation parameter?

    d) I have one heat map generated with pheatmap package and one GroupHeatMap from your package. Let’s say I have gene X for Condition 1, Condition 2, and Condition 3. From Heatmap it shows Gene X has a higher zscore for Condition 1 but in GroupHeatMap it shows Gene X has a higher zscore for Condition 3 than 1. What could be the reason for the differences between those plots?

**Comment by zhanghao-njmu** [comment]
1. `PrepareDB` function in the recent version of SCP supports the custom database. You can install the latest SCP and try the following code. 
```
## Download human hallmark gene sets and construct the "term2gene" data.frame
library(SCP)
temp <- tempfile()
gmt_url <- "https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2022.1.Hs/h.all.v2022.1.Hs.symbols.gmt"
download(url = gmt_url,destfile = temp)
custom_db <- t(read.table(temp,fill = TRUE))
colnames(custom_db) <- gsub("HALLMARK_","",custom_db[1,])
custom_db <- custom_db[-c(1:2),]
custom_db[is.na(custom_db)] <- NA
rownames(custom_db) <- NULL
term2gene <- reshape2::melt(custom_db)
term2gene <- term2gene[,2:3]
```
```
custom_db[1:5,1:5]
     TNFA_SIGNALING_VIA_NFKB HYPOXIA CHOLESTEROL_HOMEOSTASIS MITOTIC_SPINDLE WNT_BETA_CATENIN_SIGNALING
[1,] "JUNB"                  "PGK1"  "FDPS"                  "ARHGEF2"       "MYC"                     
[2,] "CXCL2"                 "PDK1"  "CYP51A1"               "CLASP1"        "CTNNB1"                  
[3,] "ATF3"                  "GBE1"  "IDI1"                  "KIF11"         "JAG2"                    
[4,] "NFKBIA"                "PFKL"  "FDFT1"                 "KIF23"         "NOTCH1"                  
[5,] "TNFAIP3"               "ALDOA" "DHCR7"                 "ALS2"          "DLL1"                    
```
```
head(term2gene)
                     Var2   value
1 TNFA_SIGNALING_VIA_NFKB    JUNB
2 TNFA_SIGNALING_VIA_NFKB   CXCL2
3 TNFA_SIGNALING_VIA_NFKB    ATF3
4 TNFA_SIGNALING_VIA_NFKB  NFKBIA
5 TNFA_SIGNALING_VIA_NFKB TNFAIP3
6 TNFA_SIGNALING_VIA_NFKB   PTGS2
```
```
## Prepare the database using the custom "term2gene"
## Note that the following code construct a Hallmark database for Mus_musculus by converting to homologous genes as well
db_list <- PrepareDB(
  species = c("Homo_sapiens", "Mus_musculus"), db = "Hallmark", convert_species = TRUE,
  custom_TERM2GENE = term2gene, custom_species = "Homo_sapiens", custom_IDtype = "symbol", custom_version = "v2022.1"
)
ListDB(db = "Hallmark")
                                                          identifier version
159 Rcache v0.1.7 (R package R.cache by Henrik Bengtsson)              0.1.7
104 Rcache v0.1.7 (R package R.cache by Henrik Bengtsson)              0.1.7
                                                                comment  timestamp                date
159                              v2022.1 nterm:50|Homo_sapiens-Hallmark 1674268388 2023-01-21 10:33:08
104 v2022.1(converted from Homo_sapiens) nterm:50|Mus_musculus-Hallmark 1674268482 2023-01-21 10:34:41
                                       db_version               db_name
159                              v2022.1 nterm:50 Homo_sapiens-Hallmark
104 v2022.1(converted from Homo_sapiens) nterm:50 Mus_musculus-Hallmark
                                                                       file
159 /home/zhanghao/.cache/R/R.cache/ea39c28f6cd628a1817933253785ae78.Rcache
104 /home/zhanghao/.cache/R/R.cache/9f751b07f5e4d699c2380d965ec9991f.Rcache
```
```
## The constructed custom database can be extracted by specifying the db name
db_list <- PrepareDB(species = c("Homo_sapiens", "Mus_musculus"), db = "Hallmark")
```
```
head(db_list[["Homo_sapiens"]][["Hallmark"]][["TERM2GENE"]])
                     Term  symbol entrez_id      ensembl_id
1 TNFA_SIGNALING_VIA_NFKB    JUNB      3726 ENSG00000171223
2 TNFA_SIGNALING_VIA_NFKB   CXCL2      2920 ENSG00000081041
3 TNFA_SIGNALING_VIA_NFKB    ATF3       467 ENSG00000162772
4 TNFA_SIGNALING_VIA_NFKB  NFKBIA      4792 ENSG00000100906
5 TNFA_SIGNALING_VIA_NFKB TNFAIP3      7128 ENSG00000118503
6 TNFA_SIGNALING_VIA_NFKB   PTGS2      5743 ENSG00000073756
head(db_list[["Mus_musculus"]][["Hallmark"]][["TERM2GENE"]])
                     Term         ensembl_id  symbol entrez_id
1 TNFA_SIGNALING_VIA_NFKB ENSMUSG00000052837    Junb     16477
2 TNFA_SIGNALING_VIA_NFKB ENSMUSG00000026628    Atf3     11910
3 TNFA_SIGNALING_VIA_NFKB ENSMUSG00000021025  Nfkbia     18035
4 TNFA_SIGNALING_VIA_NFKB ENSMUSG00000019850 Tnfaip3     21929
5 TNFA_SIGNALING_VIA_NFKB ENSMUSG00000032487   Ptgs2     19225
6 TNFA_SIGNALING_VIA_NFKB ENSMUSG00000003541    Ier3     15937
```
```
## The constructed custom database can be used in the functions with db parameter.
library(dplyr)
data("pancreas_sub")
pancreas_sub <- RunDEtest(pancreas_sub, group_by = "CellType")
de_filter <- filter(pancreas_sub@tools$DEtest_CellType$AllMarkers_wilcox, p_val_adj < 0.05 & avg_log2FC > 1)
ht1 <- ExpHeatmap(
  srt = pancreas_sub, features = de_filter$gene,feature_split = de_filter$group1, group.by = "CellType",
  anno_terms = TRUE,db=c("GO_BP","KEGG","Hallmark"),species="Mus_musculus"
)
ht1$plot
```
![image](https://user-images.githubusercontent.com/24678781/213840877-9231cbfc-5d5f-4286-8e40-30c0867f97e8.png)

2. y.min and y.max should work in the latest version. But it will discard some data points instead of arranging them at the edge of the threshold:
```
data("pancreas_sub")
ExpStatPlot(pancreas_sub, features = c("Rbp4", "Pyy"), group.by = "SubCellType")
```
![image](https://user-images.githubusercontent.com/24678781/213841272-702a0bc2-e24a-4eba-9cc2-699078a1876f.png)
`ExpStatPlot(pancreas_sub, features = c("Rbp4", "Pyy"), group.by = "SubCellType", y.min = 1, y.max = 5)`
![image](https://user-images.githubusercontent.com/24678781/213841335-2e77fd7a-eba2-4c82-a358-a68aaf0c51be.png)
3. 
a).  All `palette` parameters in the heatmap functions should be specified with a vector containing the palette name. For example, if you specify three cell_annotations `cell_annotation=c("CellType","CellCluster","Stage")`, you should use `cell_palette = c("Paired","Set1","Spectral")`. However, all `palcolor`  in the heatmap functions should be specified with a list of color vectors. Such as 
```
cell_palcolor= list(c( "#A6CEE3","#1F78B4","#B2DF8A","#33A02C"),
 c("#E41A1C","#377EB8","#4DAF4A","#984EA3","#FF7F00"),
 c("#5E4FA2","#3288BD","#66C2A5","#ABDDA4","#E6F598"))
```
b)  The background is used to emphasize groups that express genes in small numbers of cells, but with high expression (the plot shows small dots, but dark coloring).  By default `bg_alpha=0.5` is used to distinguish it from the color of the dots (it is only used as a contrast, so a separate legend is not added).
c) Violin plots in the heatmap are generated by ExpStatPlot. So theoretically there are many parameters adjustable, but considering that the heatmap already has too many parameters, no parameters have been added to control these details for the time being. I will refine these details later.
d)The heatmap functions in SCP contain the process of data processing. For example, GroupHeatmap first decides whether to correct the expression (from the counts slot or the data slot) based on the `lib_normalize` parameter, and the correction process is similar to `NormalizeData(normalization.method="RC")` in Seurat. The `base::mean` function is then used to calculate the average expression for each group. Finally, the expression matrix is processed according to the exp_method parameter (default is `zscore`) and used for visualization.

**Comment by Streisenberg** [comment]
Thank you so much for your detailed and prompt reply!
