### ISSUE TITLE
Question on how the annotation colors are set on ExpHeatmap()

### ISSUE THREAD

**Issue by jeji0209** [zhanghao-njmu/SCP#92]
Hello. Thank you for this wonderful tool :)
I have two questions on how the anno_terms = TRUE function works in ExpHeatmap().
1. How are the annotated terms selected in the plot? I have noticed that they are not exactly the first genes in the "GeneID" column of results when I run RunEnrichment() seperately with the same genesets.

2. How are the color of the letters set on Anno_Terms, and Anno_Features in ExpHeatmap()? I thought the color of the Anno_Terms and its intersecting genes within would match, but that does not seem to be the case, as some of the colors that are in annotated features are not present in annotated terms.

Thank you in advance!

**Comment by zhanghao-njmu** [comment]
1. `ExpHeatmap` uses `RunEnrichment` to perform enrichment analysis. The top terms used for display should be the same, but there was some problem with the code used for sorting that caused the order to be inconsistent, which I have fixed in the latest SCP.
![image](https://user-images.githubusercontent.com/24678781/214778247-5f7af934-7d7c-458f-afa1-c470a08cd75c.png)
![image](https://user-images.githubusercontent.com/24678781/214778124-08d4b1f1-bada-4bcb-8d42-e9693bcbda4c.png)

2. Yes. `anno_features` shows the top **key functional genes** from all statistically significant enriched terms(based on `padjustCutoff` or `pvalueCutoff` ) by functional gene score, not top terms, so it will not match the results from `anno_terms`. The color of the terms represents their `-log10(pvalue)` or `-log10(padjust)` values. But the color of the features represents the **functional gene score**. 

> If a gene _g_ occurs in a total of _n_ enriched terms, where the pvalue or padjust of the term _i_ is _p_i_, then the functional score of the gene _g_ is:
> ![image](https://user-images.githubusercontent.com/24678781/214776967-d246ef6c-9ae0-4cfb-b9bb-3f5abd85ed1f.png)
